### ISSUE TITLE
Some specific Use

### ISSUE THREAD

**Issue by KORuL** [poanetwork/hydrabadger#11]
Good evening! I have a specific question. I want to use hydrabadger is not quite standard, in previous versions it worked, and more recently ceased.

First problem: I want to send a transaction to the generate_contributions function, only when the transaction appeared on the corresponding node. But once there is no transaction, the life cycle of the hydrabadger never enters this function. Sample code corresponding to this issue below. 

![screenshot from 2018-11-08 11-08-37](https://user-images.githubusercontent.com/19871487/48221357-b34a3180-e346-11e8-972a-303959cb44bd.png)

 I modified the generate_contributions so that the transaction is sent only for every third time.
Also screenshot nod. 

![screenshot from 2018-11-08 11-12-57](https://user-images.githubusercontent.com/19871487/48221576-4e430b80-e347-11e8-8512-9a21d91b81c5.png)

Tell me how to be in this situation?

The second problem: I want to receive confirmed transactions, below is an example of code that worked in older versions of hydrabadger, how to do it right now?
![screenshot from 2018-11-08 11-15-00](https://user-images.githubusercontent.com/19871487/48221697-9eba6900-e347-11e8-9864-fddf6f8c0922.png)
To do this, I modified impl <T: Contribution> Future for Handler <T>, and added the following code in the screenshot to the while let some (mut step) = self.step_queue.try_pop () block, which receives the textual contents of the transaction and passes it on callback. Whether prompt a place and a method for reception of contents of transactions? Method batch.is_empty() is unreachable now, what can i do?

**Comment by c0gent** [comment]
First let me just say that as hydrabadger is in a heavy state of flux, everything I'm about to tell you could be outdated at any time. Once things start to stabilize I will write up some proper documentation.

For now, the correct way to input transactions into hydrabadger is to use the `Hydrabadger::propose_user_contribution` method. `::generate_contributions` is a temporary method meant for testing and demonstrations which will be removed at some point.

In order to receive output, you must call the `::batch_rx` method which will return a stream (receiver) which you can poll for output batches.

That is the current API for proposing contributions (transactions) and receiving the output.

Please let me know if that helps.

**Comment by KORuL** [comment]
Thank you very much for the answer, he clarified the situation), but a number of questions remained.

I want to use hydrabadger as a dll, with a method to send a transaction and callback to accept a new transaction. I used to store the object on hydrabadger in this form
at
struct Session {
    handler: Arc <Mutex <Option <Hydrabadger >>>,
}

And now the <T> template appeared in the new API, but since I’m jerking this imp from java, I cannot make it template-based, how can I save a hydrabadger object of a certain type already?

Hydrabadger :: propose_user_contribution - if the node is not a validator, then an error will occur, where can I get an event that it’s time to send a transaction using this method?

And accordingly, you need to find out a place where you can call a callback with a transaction if it is available.

**Comment by c0gent** [comment]
> Hydrabadger :: propose_user_contribution - if the node is not a validator, then an error will occur, where can I get an event that it’s time to send a transaction using this method?

`Hydrabadger::is_validator` will tell you whether or not you can propose a contribution.

As for the rest of your question, I'm not entirely sure what you're asking but let's see...

> I want to use hydrabadger as a dll, with a method to send a transaction and callback to accept a new transaction. I used to store the object on hydrabadger in this form
at
struct Session {
    handler: Arc <Mutex <Option >>,
}

When you say "I used to store the object on hydrabadger in this form", what do you mean by "object"?

> And now the template appeared in the new API, but since I’m jerking this imp from java, I cannot make it template-based, how can I save a hydrabadger object of a certain type already?

What is the "template" that you are referring to?

It looks like you're trying to make a Java API for this, which means you'll need to make a C API. Proposing contributions should be relatively straightforward (just add a wrapper function for `propose_user_contribution`). Receiving batch outputs will be more tricky. You'll need to handle the `batch_rx` stream output and call a pre-configured callback function which accepts a batch as the argument.

How familiar are you with [ffi in Rust](https://doc.rust-lang.org/book/second-edition/ch19-01-unsafe-rust.html#using-extern-functions-to-call-external-code)?

**Comment by KORuL** [comment]
I am not good at rusting, so I can call the wrong definitions.  I have already partially understood the part of C Api and its interaction. I called the habit template from c ++ <T> in the struct and impl, and the object was the handler from the struct Session.

In theory, the struct Session handler should have the following form:
handler: Arc <Mutex <Option <Hydrabadger <T >>>>,
but then there must be a struct Session <T>, and for a link from c ++, the struct Session must be without <T>

how do i create a handler in impl session?

Sorry for the question not related to the topic of Hydrabadger, but my rust level does not reach <T> (

**Comment by c0gent** [comment]
>  I called the habit template from c ++ <T> in the struct and impl, and the object - was the handler from the struct Session.

I'm not sure what you mean by "habit template".

Keep in mind, for Rust FFI you will be creating a C interface, not a C++ interface. That means that you cannot use generics so there will be no `<T>`, you will instead create a `Hydrabadger<Transaction>` where `Transaction` is usually serialized into a `Vec<u8>`. So you might want to use a `Hydrabadger<Vec<u8>>`.

**Comment by KORuL** [comment]
Oh thanks! You answered my question)

**Comment by KORuL** [comment]
I discovered the following thing:
if only one node generates transactions in this form, as in the screenshot, they will not come to the other nodes. Transactions will come if only all nodes generate transactions using this method.
![screenshot from 2018-11-10 11-45-09](https://user-images.githubusercontent.com/19871487/48305392-7a44c500-e4de-11e8-853b-1819a25f0583.png)

**Comment by KORuL** [comment]
In generate_contributions i comment generating

**Comment by c0gent** [comment]
Apologies for taking so long to respond.

Could you please clarify what you mean in your previous comments?

**Comment by KORuL** [comment]
Hello! Many of my problems disappeared with the hydrabadger update/

I. The problem remained with the obligatory sending of transactions:
I run the first node `./run-node 0`
Then i comment
```
                         hdb.send_internal (InternalMessage :: hb_contribution (
                             hdb.inner.uid,
                             OutAddr (* hdb.inner.addr),
                             txns
                         ))
```
and run
`./run-node 1`
`./run-node 2`
and I see the following log:

![screenshot from 2018-11-17 01-01-49](https://user-images.githubusercontent.com/19871487/48659352-9ad1c980-ea60-11e8-849d-4cb6a836e119.png)

that is, the first node stopped generating and sending transactions.

II. The second problem will probably disappear when the first one is solved, it is connected with the use of the `propose_user_contribution function`
If you remove the generation of transactions of each node as it is now, and instead add the sending of transactions through `propose_user_contribution`, then the transactions do not go.  Or rather, if the three nodes in turn called `propose_user_contribution`, then the transaction will appear in reverse order or some may not come at all

**Comment by afck** [comment]
Yes, a node that doesn't have any transactions has to either wait a bit and stall the network or propose an _empty_ contribution. Exactly what the policy should be here is an application-level decision, but it's important to keep in mind that
* in every epoch, every validator can make _one_ contribution (any further ones are ignored, and I think we return an error for that),
* the epoch only ends when more than ⅔ of the validators have made their contribution.

So you need to implement a transaction queue, and whenever a new epoch begins, you make a single contribution, which is a list of transactions.

An example policy that we [implemented in `QueueingHoneyBadger`](https://github.com/poanetwork/hbbft/blob/master/src/queueing_honey_badger/mod.rs#L301) is to wait after every batch until:
* You have at least one transaction in the queue (so your contribution wouldn't be empty), or
* you have a pending vote or distributed key generation (DKG) message because we're in the process of adding or removing validators, or
* at least ⅓ of the validators validators have already made their contribution.

Once one of these criteria is satisfied, we make a (possibly empty) contribution. The idea behind the third point is that even if you have nothing (no votes, DKG messages or transactions) to contribute, at that point you know that at least one correct node does have something. The [`DynamicHoneyBadger::should_propose`](https://github.com/poanetwork/hbbft/blob/master/src/dynamic_honey_badger/dynamic_honey_badger.rs#L185) method helps detect the second and third point. (Not sure whether that's currently accessible via Hydrabadger, @c0gent?)

Anyway: A 3-node network won't make progress and won't output a batch unless all three nodes make a contribution. If a node tries to make more than one contributions per epoch, all but the first one are ignored.

Also, the contributions in the batch are actually in a map, by proposer. The order in general isn't the order in which the nodes made their contributions because in an asynchronous network that can't be known.
