### ISSUE TITLE
Empty transaction

### ISSUE THREAD

**Issue by KORuL** [poanetwork/hydrabadger#25]
Hi! We use this repo for creating crypto-based messenger app. The are some issues and improvements suggestoins we want to introduce. It would be cool if you add the following capablities we need:

- Hydrabadger must send an empty transaction by itself within the absence of transaction from the user. It would be more suitable if Hydrabadger did not send nothing in this case.

**Comment by c0gent** [comment]
@KORuL, If you can provide a few more details on precisely how you see this working I can add something.

**Comment by KORuL** [comment]
I would like the object of hydrabadger to have an API to send a transaction, and it would not be necessary to call this function at each epoch. Roughly speaking, if there is a transaction at my level - I call the function send_transaction (tr: Transaction), if there is no transaction, then hydrabadger would automatically send an empty transaction, liyuo somehow resolved this issue

**Comment by c0gent** [comment]
So a configurable setting like `maximum_epoch_time` where after a certain amount of time has elapsed an empty contribution is submitted?

**Comment by afck** [comment]
It sounds like you want something like [`QueueingHoneyBadger`](https://github.com/poanetwork/hbbft/blob/d4a7b19adb7021efcefdf735f6dd2c45cce0a1d2/src/queueing_honey_badger/mod.rs#L155), that collects transactions you input, and in each epoch sends all transactions that are currently in the queue. We decided against using that in hydrabadger, though, precisely because it's hard to make it customizable enough to suit all use-cases. It's better if the application logic decides how it wants to handle epochs and when it wants to start a new one.

I'm not even sure what the right policy for a messenger app would be: Here we want messages to arrive with low latency, and spam protection and empty batches are less of an issue. So maybe something like this:
* Whenever you have at least one message in your queue, include all messages in your contribution. (Because you want messages to be sent instantly, without additional delay.)
* If your queue is empty but a contribution from a peer for the next epoch arrives, make an empty contribution. (You don't want to delay the peer just because your own user didn't type anything.)
* Maybe some mild spam protection: Don't send and accept contributions larger than some limit.

The second point is a bit tricky; I think we should [add an `fn honey_badger(&self)` getter](https://github.com/poanetwork/hbbft/issues/381) to `DynamicHoneyBadger`; with that, you could get the number of peers who have sent a contribution like this:
```rust
hydrabadger.state().dhb().honey_badger().received_proposals()
```

**Comment by KORuL** [comment]
#24  Issues united in essence
