### ISSUE TITLE
Blockchain wasn't really used

### ISSUE THREAD

**Issue by LuminousXLB** [poanetwork/hydrabadger#31]
I'm looking for a way to verify transacations during the consensus using `hbbft`. 

When exploring hydrabadger, I found that `pub struct Blockchain` was only used by `fn mine() -> Result<(), MiningError>`. However, the function `mine` wasn't really called anywhere.

Is that true and could you please offer any support on embedding our own verify procedure in `hbbft`.

Thanks

**Comment by c0gent** [comment]
Unfortunately this project is in an incomplete state (and the mining code was not meant to actually be used). You may want to ask for help in the [hbbft](https://github.com/poanetwork/hbbft) repo as this project is largely unmaintained.

**Comment by afck** [comment]
Also note that hbbft encrypts the transactions; they are only decrypted _after_ consensus has been reached. Before that, the other validators don't even get to see them.

So I'd suggest a verification in two stages:
* The node that proposes the transaction is required to verify them first.
* After consensus has been reached, every node verifies all transactions, and filters out invalid ones.

After the second step, the nodes that contributed invalid transactions can be banned, since they failed to perform the first step.
